/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaylistItem } from './playlistItem';


/**
 * רשימת השמעה עם פריטים מסודרים.
 */
export interface Playlist { 
    id: number;
    name: string;
    userId: number;
    createdAt?: string;
    /**
     * הסדר נשמר בעזרת טבלת קישור (PlaylistSong) ב־DB
     */
    items?: Array<PlaylistItem>;
}

