/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * פריט ברשימת השמעה (שומר פריטים מסודרים לפי order).
 */
export interface PlaylistItem { 
    songId: number;
    title?: string | null;
    artist?: string | null;
    /**
     * מיקום ברשימה (0-based או 1-based — תבחר כללים)
     */
    order: number;
}

