/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ייצוג טוקן רפרש (לשימוש פנימי/DB).
 */
export interface RefreshTokenEntity { 
    token: string;
    deviceId?: string | null;
    createdAt: string;
    expiresAt: string;
    revokedAt?: string | null;
    isActive?: boolean;
}

