/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ייצוג שיר שמוחזר ללקוח.
 */
export interface Song { 
    id: number;
    title: string;
    artist: string;
    album?: string | null;
    /**
     * אורך השיר בשניות
     */
    durationSeconds: number;
    /**
     * כתובת לזרם/קובץ
     */
    streamUrl?: string | null;
    createdAt?: string;
}

