/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponse { 
    accessToken?: string;
    refreshToken?: string;
    /**
     * משך חיים של ה־access token בשניות
     */
    expiresIn?: number;
}

