/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload לרישום — הסיסמה רק לכתיבה.
 */
export interface UserCreate { 
    userName: string;
    email: string;
    /**
     * Plain password — יש לאחסן hash+salt בשרת
     */
    password: string;
}

