/**
 * Music API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User שניתן להחזיר ללקוח (לא מכיל סיסמא/סולט).
 */
export interface UserPublic { 
    /**
     * Primary key
     */
    id: number;
    userName: string;
    email: string;
    createdAt?: string;
}

